# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  apigateway:
    build:
      context: "D:\\Projects\\Kira"
      dockerfile: "src/ApiGateways/Kira.ApiGateway.Ocelot/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "kiraapigatewayocelot:dev"
    ports:
    - "127.0.0.1:49739:57100"
    - "127.0.0.1:57212:57300"
    volumes:
    - "C:\\Users\\Raf\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Kira\\src\\ApiGateways\\Kira.ApiGateway.Ocelot:/app:rw"
    - "D:\\Projects\\Kira:/src:rw"
    - "C:\\Users\\Raf\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "D:\\Programs\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Raf\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_2_27_03_04_45:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  flightservice:
    build:
      context: "D:\\Projects\\Kira"
      dockerfile: "src/Services/FlightService/Kira.Flight.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "kiraflightserviceapi:dev"
    ports:
    - "127.0.0.1:49740:57100"
    - "127.0.0.1:57213:57300"
    volumes:
    - "C:\\Users\\Raf\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Kira\\src\\Services\\FlightService\\Kira.Flight.API:/app:rw"
    - "D:\\Projects\\Kira:/src:rw"
    - "C:\\Users\\Raf\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "D:\\Programs\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Raf\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_2_27_03_04_45:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  identityservice:
    build:
      context: "D:\\Projects\\Kira"
      dockerfile: "src/Services/IdentityService/Kira.IdentityService.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "kiraidentityserviceapi:dev"
    ports:
    - "127.0.0.1:49741:57100"
    - "127.0.0.1:57214:57300"
    volumes:
    - "C:\\Users\\Raf\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Kira\\src\\Services\\IdentityService\\Kira.IdentityService.API:/app:rw"
    - "D:\\Projects\\Kira:/src:rw"
    - "C:\\Users\\Raf\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "D:\\Programs\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Raf\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_2_27_03_04_45:/var/opt/rider-debugger:rw"
    working_dir: "/app"
