version: '3.4'

services:
  kira.identityservice.api:
    image: ${DOCKER_REGISTRY-}kiraidentityserviceapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/Kira.IdentityService.API/Dockerfile
    ports:
      - "5086:80"
    networks:
      - gatewaynetwork
      - identitynetwork
    depends_on:
      - identitydb
  kira.apigateway.ocelot:
    image: ${DOCKER_REGISTRY-}kiraapigatewayocelot
    build:
      context: .
      dockerfile: src/ApiGateways/Kira.ApiGateway.Ocelot/Dockerfile
    ports:
      - "5266:80"
    networks:
      - gatewaynetwork
      - frontendnetwork
    depends_on:
      - kira.identityservice.api
  identitydb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: identitydb
    ports:
      - "1433:1433"
    networks:
      - identitynetwork
  
networks:
  frontendnetwork:
  gatewaynetwork:
  identitynetwork: