version: '3.4'

services:
  identitydb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin1234!
      - POSTGRES_DB=IdentityDatabase
    volumes:
      - postgres_identity_data:/var/lib/postgresql/data/
  flightdb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin1234!
      - POSTGRES_DB=FlightDatabase
    volumes:
      - postgres_flight_data:/var/lib/postgresql/data/
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes:
      - pgadmin_data:/root/.pgadmin
  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  flightservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  postgres_identity_data:
  postgres_flight_data:
  pgadmin_data:
    