version: '3.4'

services:
  identitydb:
    image: postgres
    container_name: identitydb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - identitynetwork
  flightdb:
    image: postgres
    container_name: flightdb
    restart: always
    ports:
      - "5555:5432"
    networks:
      - flightnetwork
  identityservice:
    image: ${DOCKER_REGISTRY-}kiraidentityserviceapi
    container_name: identityservice
    build:
      context: .
      dockerfile: src/Services/IdentityService/Kira.IdentityService.API/Dockerfile
    ports:
      - "5086:80"
    networks:
      - identitynetwork
      - gatewaynetwork
    depends_on:
      - identitydb
  flightservice:
    image: ${DOCKER_REGISTRY-}kiraflightserviceapi
    container_name: flightservice
    build:
      context: .
      dockerfile: src/Services/FlightService/Kira.Flight.API/Dockerfile
    ports:
      - "5247:80"
    networks:
      - flightnetwork
      - gatewaynetwork
    depends_on:
      - flightdb
  apigateway:
    image: ${DOCKER_REGISTRY-}kiraapigatewayocelot
    container_name: apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/Kira.ApiGateway.Ocelot/Dockerfile
    ports:
      - "5266:80"
    networks:
      - gatewaynetwork
      - identitynetwork
      - flightnetwork
    depends_on:
      - identityservice
      - flightservice
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
networks:
  identitynetwork:
    driver: bridge
  flightnetwork:
    driver: bridge
  gatewaynetwork:
    driver: bridge
    