version: '3.4'

services:
  identitydb:
    image: postgres
    container_name: identitydb
    restart: always
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U admin"]
    #  interval: 20s
    # timeout: 10s
    # retries: 5
    ports:
        - "5432:5432"
  identityservice:
    image: ${DOCKER_REGISTRY-}kiraidentityserviceapi
    container_name: identityservice
    build:
      context: .
      dockerfile: src/Services/IdentityService/Kira.IdentityService.API/Dockerfile
    ports:
      - "5086:80"
    depends_on:
      - identitydb
      #  condition: service_healthy
  apigateway:
    image: ${DOCKER_REGISTRY-}kiraapigatewayocelot
    container_name: apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/Kira.ApiGateway.Ocelot/Dockerfile
    ports:
      - "5266:80"
    depends_on:
      - identityservice
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
        - "5050:80"
    